### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by kbknapp** [clap-rs/clap_derive#7]
Pulled from #6 

> Should clap-derives be usable on clap 2.x?
> I'm leaning yes, because what you've done already works today. I also think we should be pushing towards a clap-derives which works on clap 3.x which this issue is aimed at.
> So I think we need to find a way to differentiate between these two branches.

I'm proposing:

* Initial push for this crate should be get it *releasable* on clap 2.x
* All initial development of this crate is released as 0.x.y
* Once we're comfortable with everything, we release a version pinned to the current clap *major* version it targets (i.e. 2.0). As not every clap release will require a new clap-derives release, but he majors should be in sync
* This initial push can very well include all the common `structopt` features.
* All future work to get this to work on clap 3.x would be done on a separate branch
* Once clap 3.x is releasable, and clap-derives is matching we release 3.0.0 of *both* crates.

---

This creates a little confusion at first. But I think in the long run it'll be far easier for people to track what fits with what. Other popular crates in the ecosystem take this approach as well.

---

Whatever we decide, we should put a blurb about this in the readme so people know what to expect.

**Comment by pksunkara** [comment]
We have decided to have clap_derive only as part of 3.0 clap release.
